Repository kitajs/kitajs, pull requests merged in 2024-04, with the labels that each got.

#365 Project Naming and Path Resolution Enhancements
  .changeset/early-turkeys-deliver.md
  packages/cli/src/commands/create.ts
Labels: bug

#374 Improved kita-jsx template landing page
  .changeset/healthy-suns-laugh.md
  packages/cli/templates/kita-jsx/src/components/layout.tsx
  packages/cli/templates/kita-jsx/src/routes/index.tsx
Labels: enhancement

#432 Migrated to an entire sync api
  .changeset/moody-bikes-impress.md
  .vscode/settings.json
  packages/common/src/ast/collector.ts
  packages/common/src/ast/formatter.ts
  packages/common/src/ast/provider.ts
  packages/common/src/parsers/chain.ts
  packages/common/src/parsers/parser.ts
  packages/common/src/util/index.ts
  packages/common/src/util/promises.ts
  packages/generator/src/formatter.ts
  packages/generator/test/runner.ts
  packages/parser/src/parameter-parsers/chain.ts
  packages/parser/src/parameter-parsers/custom.ts
  packages/parser/src/parser.ts
  packages/parser/src/provider-parsers/chain.ts
  packages/parser/src/provider-parsers/default.ts
  packages/parser/src/provider-parsers/schema.ts
  packages/parser/src/route-parsers/chain.ts
  packages/parser/src/route-parsers/html.ts
  packages/parser/src/route-parsers/rest.ts
  packages/parser/src/util/traverser.ts
  packages/parser/test/body-prop/index.test.ts
  packages/parser/test/body/index.test.ts
  packages/parser/test/cookies/index.test.ts
  packages/parser/test/default-export/index.test.ts
  packages/parser/test/errors/index.test.ts
  packages/parser/test/file/index.test.ts
  packages/parser/test/header/index.test.ts
  packages/parser/test/hello-world/index.test.ts
  packages/parser/test/html/index.test.ts
  packages/parser/test/invalid-parameter/index.test.ts
  packages/parser/test/jsdoc/index.test.ts
  packages/parser/test/method-all/index.test.ts
  packages/parser/test/methods/index.test.ts
  packages/parser/test/multiple-paths/index.test.ts
  packages/parser/test/paths/index.test.ts
  packages/parser/test/provider-effects/index.test.ts
  packages/parser/test/provider-hooks/index.test.ts
  packages/parser/test/provider/index.test.ts
  packages/parser/test/providers-registration/index.test.ts
  packages/parser/test/query/index.test.ts
  packages/parser/test/ref-types/index.test.ts
  packages/parser/test/runner.ts
  packages/parser/test/schemas-provider/index.test.ts
  packages/parser/test/this/index.test.ts
  packages/parser/test/throws-sensible/index.test.ts
  packages/parser/test/void-return/index.test.ts
  packages/parser/test/wildcard-routes/index.test.ts
  packages/ts-plugin/package.json
  packages/ts-plugin/src/parsers/provider.ts
  packages/ts-plugin/src/parsers/route.ts
  packages/ts-plugin/src/util/sync.ts
  pnpm-lock.yaml
Labels: enhancement, good first issue
